
src = ["cwrap"]
line-length = 88

[lint]
select = [
  "W",   # pycodestyle
  "I",   # isort
  "B",   # flake-8-bugbear
  "SIM", # flake-8-simplify
  "F",   # pyflakes
  "UP",
  "PL",  # pylint
]

ignore = ["PLW2901", # redefined-loop-name
          "PLR2004", # magic-value-comparison
          "PLR0915", # too-many-statements
          "PLR0912", # too-many-branches
          "PLR5501", # collapsible-else-if
          "PLR0911",  # too-many-return-statements
]